## Circle Area

In [14]:
import numpy as np
def circle_area():
    radius=float(input('what the area radius? '))
    # Area = πr²
    area=(np.pi) * (radius**2)  
    print(f'circle area = {area}')
    
circle_area()                    

what the area radius? 2
circle area = 12.566370614359172


## Parallelogram Area

In [15]:
def parallelogram_area():
    base = float(input('what is the base? '))
    height=float(input('what is the height? '))
    # A = bh
    area = base * height
    print(f'parallelogram area = {area}')
    
parallelogram_area()

what is the base? 2
what is the height? 8
parallelogram area = 16.0


## Trapezoid Area

In [16]:
def trapezoid_area():
    short_base=float(input('what is the short base? '))
    long_base=float(input('what is the long base? '))
    height=float(input('what is the height? '))
    # A = (a+b)/2 * h
    area= (short_base+long_base)/2 * height
    print(f'trapezoid area = {area}')

trapezoid_area()

what is the short base? 3
what is the long base? 7
what is the height? 5
trapezoid area = 25.0


## Standard deviation

In [17]:
def standard_deviation():
    array_length=int(input('total number of array elements: '))
    array=[]
    for i in range(array_length):
        array.append(float(input(f'array element {i}: ')))
    
    # σ = squre_root(∑( X − μ )²/ n)
    mean=sum(array)/array_length
    squared_difference=0
    for i in array:
        squared_difference +=(i-mean)**2
    standard_deviation = np.sqrt(squared_difference/array_length)
    print(f'standard deviation = {standard_deviation}')
    
standard_deviation()

total number of array elements: 8
array element 0: 10
array element 1: 12
array element 2: 23
array element 3: 23
array element 4: 16
array element 5: 23
array element 6: 21
array element 7: 16
standard deviation = 4.898979485566356


## Correlation Coefficient

In [20]:
def correlation_coefficient():
    array_length=int(input('sample size: '))
    first_array=[]
    second_array=[]
    for i in range(array_length):
        first_array.append(float(input(f'first array element {i}: ')))
    for j in range(array_length):
        second_array.append(float(input(f'second array element {j}: ')))
        
    # r= (∑(x − X)(y-Y))/square_root(∑(x − X)² ∑( y − Y)²)
    first_array_mean=sum(first_array)/array_length
    second_array_mean=sum(second_array)/array_length
    x_y_difference=0
    x_squared_difference=0
    y_squared_difference=0
    for i,j in zip(first_array,second_array):
        x_y_difference += (i-first_array_mean)*(j-second_array_mean)
        x_squared_difference += (i-first_array_mean)**2
        y_squared_difference += (j-second_array_mean)**2
    correlation_coefficient = (x_y_difference)/np.sqrt(x_squared_difference*y_squared_difference)
    
    print(f'correlation coefficient = {correlation_coefficient}')
    
correlation_coefficient()

sample size: 5
first array element 0: 2
first array element 1: 4
first array element 2: 6
first array element 3: 1
first array element 4: 4
second array element 0: 11
second array element 1: 6
second array element 2: 17
second array element 3: 3
second array element 4: 4
correlation coefficient = 0.6097367084753432


## Insertion Sort

In [21]:
def insertion_sort():
    array_length=int(input('total number of array elements: '))
    array=[]
    for i in range(array_length):
        array.append(int(input(f'array element {i}: ')))
        
    # loop on every element in the array starting from second element
    # store the elemnt in temporary variaable
    for i in range(1,array_length):
        k=array[i]
        # loop on all previous elemnts
        for j in range(i-1,-1,-1):
            # check if previus is bigger
            if array[j] > k:
                array[j+1]=array[j]
            else:
                break
            array[j]=k
            
    print(f'sorted array is: {array}')

insertion_sort()

total number of array elements: 9
array element 0: 16
array element 1: 27
array element 2: 19
array element 3: 2
array element 4: 30
array element 5: 10
array element 6: 10
array element 7: 27
array element 8: 55
sorted array is: [2, 10, 10, 16, 19, 27, 27, 30, 55]


## Merge Sort

In [22]:
def merge_sort(array):
    
    # recursion
    # check baase condition
    if len(array) > 1:
        # divide and conquer
        mid = len(array)//2
        left_array=array[:mid]
        right_array=array[mid:]
        merge_sort(left_array)
        merge_sort(right_array)
        # temporary variables for looping
        i=j=k=0
        while i < len(left_array) and j < len(right_array):
            if left_array[i] < right_array[j]:
                array[k] = left_array[i]
                i+=1
                k+=1
            else:
                array[k] = right_array[j]
                j+=1
                k+=1
        while i < len(left_array):
            array[k]=left_array[i]
            i+=1
            k+=1
        while j < len(right_array):
            array[k]=right_array[j]
            j+=1
            k+=1
            
    return f'sorted array = {array}'

merge_sort([2,5,1,9,7,12])

'sorted array = [1, 2, 5, 7, 9, 12]'

## Binary Search

In [23]:
def binary_search(array,item):
    # inputs
    # function arguments: sorted array and item to search for
    
    # process
    # divide the array and check at the mid point
    low = 0
    high = len(array) - 1
    while low <= high:
        mid = (low + high) // 2
        if item == array[mid]:
            return mid
        else:
            if item > array[mid]:
                low = mid + 1
            else:
                high = mid - 1
    return 'Not found'
            
binary_search([2,5,8,10],700),binary_search([23,28,66,101],28)

('Not found', 1)

## Segregate Positive and Negative Numbers

In [24]:
def segregate_positive_negative(array):
    # input
    # array of positive and negative numbers in function arguments
    
    # process
    # using merge sort 
    if len(array) > 1:
        mid=len(array)//2
        left_array=array[:mid]
        righ_array=array[mid:]
        segregate_positive_negative(left_array)
        segregate_positive_negative(righ_array)
        i=j=k=0
        while i < len(left_array) and j < len(righ_array):
            if left_array[i] < 0:
                array[k]=left_array[i]
                i+=1
                k+=1
            elif righ_array[j] < 0:
                array[k]=righ_array[j]
                j+=1
                k+=1
            else:
                break
        while i < len(left_array):
            array[k]=left_array[i]
            i+=1
            k+=1
        while j < len(righ_array):
            array[k]=righ_array[j]
            j+=1
            k+=1
                
    return f'segregated array = {array}'

segregate_positive_negative([2,4,-2,5,-3,6,9,-1,-11])
            

'segregated array = [-2, -3, -1, -11, 2, 4, 5, 6, 9]'

## Greedy Algorithm- Activity Selection Problem

In [25]:
# class for activity[name,start time,end time]
class Activity():
    def __init__(self,name,start=0,end=0):
        self.name=name
        self.start=start
        self.end=end
A,B,C=Activity('A',9,11),Activity('B',10,11),Activity('C',11,12)
D,E,F=Activity('D',12,14),Activity('E',13,15),Activity('F',15,16)
all_activities=[A,B,C,D,E,F]

def select_activities(activities):
    selected=[activities[0].name]
    for i in range(1,len(activities)):
        if activities[i].start >= activities[i-1].end:
            selected.append(activities[i].name)
    
    return f'selected activites = {selected}'

select_activities(all_activities)

"selected activites = ['A', 'C', 'D', 'F']"

## Greedy Algorithm - Sorted Characters Frequencies

### ASCII-Characters

In [26]:
import numpy as np
def ASCIIMethod(string):
    # ASCII encode all english characters and numbers and special characters in 128 code starting from 0 to 127
    # start  empty array of same size
    char_freq=np.zeros(127)
    for i in string:
        current_code=ord(i)  # covert the character to its code in ASCII
        char_freq[current_code]+=1   # increase its value in the freq array
    frequency={}    
    for j in range(len(char_freq)):
        if char_freq[j]>0:
            frequency[chr(j)]=char_freq[j]
    frequency_list=[[i,j] for i , j in frequency.items()]
           
    def merge_sort(array):
        if len(array) > 1:
            midpoint=len(array)//2
            left_array=array[:midpoint]
            right_array=array[midpoint:]
            merge_sort(left_array)
            merge_sort(right_array)
            i=j=k=0
            while i< len(left_array) and j < len(right_array):
                if left_array[i][1]<right_array[j][1]:
                    array[k]=left_array[i]
                    i+=1
                    k+=1
                else:
                    array[k]=right_array[j]
                    j+=1
                    k+=1
            while i < len(left_array):
                array[k]=left_array[i]
                i+=1
                k+=1
            while j < len(right_array):
                array[k]=right_array[j]
                j+=1
                k+=1
        return array
    return (merge_sort(frequency_list))
           
ASCIIMethod('hello world')

[['w', 1.0],
 ['r', 1.0],
 ['h', 1.0],
 ['e', 1.0],
 ['d', 1.0],
 [' ', 1.0],
 ['o', 2.0],
 ['l', 3.0]]

### UTF-8

In [27]:
def word_count_sorted(string):
    freq={}
    for i in string:
        if i not in freq.keys():
            freq[i]=1
        else:
            freq[i]+=1
        counted_list=[[i,j] for i,j in freq.items()]

    def merge_sort(array):
        if len(array) > 1:
            midpoint=len(array)//2
            left_array=array[:midpoint]
            right_array=array[midpoint:]
            merge_sort(left_array)
            merge_sort(right_array)
            i=j=k=0
            while i< len(left_array) and j < len(right_array):
                if left_array[i][1]<right_array[j][1]:
                    array[k]=left_array[i]
                    i+=1
                    k+=1
                else:
                    array[k]=right_array[j]
                    j+=1
                    k+=1
            while i < len(left_array):
                array[k]=left_array[i]
                i+=1
                k+=1
            while j < len(right_array):
                array[k]=right_array[j]
                j+=1
                k+=1
        return array
    return merge_sort(counted_list)

word_count_sorted('hello world')     

[['d', 1],
 ['r', 1],
 ['w', 1],
 [' ', 1],
 ['e', 1],
 ['h', 1],
 ['o', 2],
 ['l', 3]]

## Greedy Algorithm-Huffman Encoding

In [28]:
from heapq import heapify, heappop,heappush
def huffman_encoding(string):
    counter={}
    for i in string:
        if i not in counter.keys():
            counter[i]=1
        else:
            counter[i]+=1
    minheap=[[freq,[data,'']] for data,freq in counter.items()]
    heapify(minheap)
    while len(minheap) > 1:
        left_node=heappop(minheap)
        right_node=heappop(minheap)
        for data in left_node[1:]:
            data[1]='0'+data[1]
        for data in right_node[1:]:
            data[1]='1'+data[1]
        heappush(minheap,[left_node[0]+right_node[0]]+left_node[1:]+right_node[1:])
        huffman_list = right_node[1:] + left_node[1:]
    return huffman_list
huffman_encoding('internet')

[['n', '10'], ['t', '11'], ['e', '00'], ['i', '010'], ['r', '011']]

## Greedy Algorithm- Fractional knapsack Problem

In [29]:
names=['a','b','c','d','e','f']
weights=[1,2,10,4,3,5]
values=[4,9,12,11,6,5]
ratios=[i/j for i,j in zip(values,weights)]
data=[[a,b,c,d] for a,b,c,d in zip(names,weights,values,ratios)]
data.sort(key=lambda x:x[3],reverse=True)
def knapsac_fill(data,k):
    curent_weight=0
    avaliable_weight=k-curent_weight
    knapsack=[]
    while curent_weight < k:
        for i in data:
            if i[1]<= avaliable_weight:
                knapsack.append(i)
                curent_weight+=i[1]
                avaliable_weight-=i[1]
            else:
                i[1]=avaliable_weight
                i[2]=avaliable_weight * i[3]
                knapsack.append(i)
                curent_weight+=i[1]
                avaliable_weight-=i[1]
                break
    return knapsack

knapsac_fill(data,12)                

[['b', 2, 9, 4.5],
 ['a', 1, 4, 4.0],
 ['d', 4, 11, 2.75],
 ['e', 3, 6, 2.0],
 ['c', 2, 2.4, 1.2]]

## Dynamic Programming-Stagecoach Problem

In [30]:
labels=list(map(chr,range(ord('A'),ord('J')+1)))
A=[['B','C','D'],[2,4,3]]
B=[['E','F','G'],[7,4,6]]
C=[['E','F','G'],[3,2,4]]
D=[['E','F','G'],[4,1,5]]
E=[['H','I'],[1,4]]
F=[['H','I'],[6,3]]
G=[['H','I'],[3,3]]
H=[['J'],[3]]  
I=[['J'],[4]] 
all_routes=[
           [0,A[1][0],A[1][1],A[1][2],0,0,0,0,0,0],
            [0,0,0,0,B[1][0],B[1][1],B[1][2],0,0,0],
            [0,0,0,0,C[1][0],C[1][1],C[1][2],0,0,0],
            [0,0,0,0,D[1][0],D[1][1],D[1][2],0,0,0],
            [0,0,0,0,0,0,0,E[1][0],E[1][1],0],
            [0,0,0,0,0,0,0,F[1][0],F[1][1],0],
            [0,0,0,0,0,0,0,G[1][0],G[1][1],0],
            [0,0,0,0,0,0,0,0,0,H[1][0]],
            [0,0,0,0,0,0,0,0,0,I[1][0]],
             [0,0,0,0,0,0,0,0,0,0]]
def find_min_route(routes):
    
    minimum_route=routes[-1]
    minimum_route[-1]={'from':'','to':'','cost':0}
    max_num=float('inf')
    for i in range(len(routes)-2,-1,-1):
        minimum_route[i]={'from':labels[i],'to':labels[i+1],'cost':max_num}
        for j in range(i+1,len(routes)):
            if routes[i][j]==0:
                continue
            newcost=routes[i][j]+minimum_route[j]['cost']
            if newcost< minimum_route[i]['cost']:
                minimum_route[i]['to']=labels[j]
                minimum_route[i]['cost']=newcost
            
    optimum_route=['A']
    for i in minimum_route:
        if i['from']=='A':
            optimum_route.append(i['to'])
            x=i['to']
        else:
            if i['from']==x:
                optimum_route.append(i['to'])
                x=i['to']
    print(f'optimum route is: {optimum_route}')
    print('cost : ',minimum_route[0]['cost'])
    
    
find_min_route(all_routes)

optimum route is: ['A', 'C', 'E', 'H', 'J']
cost :  11


## Dynamic Programming-Longest Common Subsequence Problem

In [31]:
import numpy as np
def Longest_common_subsequence(string1,string2):
    table=np.zeros((len(string2)+1,len(string1)+1))
    for i in range(1,len(string2)+1):
        for j in range(1,len(string1)+1):
            if string2[i-1]!=string1[j-1]:
                table[i,j]=max(table[i-1,j],table[i,j-1])
            else:
                table[i,j]=1+table[i-1,j-1]
    print(table)
    i=len(string2)
    j=len(string1)
    long_string=''
    while i > 0 and j > 0:
        if table[i,j]>table[i,j-1]:
            if table[i,j]==table[i-1,j]:
                i-=1
            else:
                long_string=string2[i-1]+long_string
                i-=1
                j-=1
        else:
            j-=1
    print('longest common subsequent string is : ',long_string)
    
Longest_common_subsequence('helloworld','ohelod')

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [0. 1. 2. 3. 3. 3. 3. 3. 3. 3. 3.]
 [0. 1. 2. 3. 3. 4. 4. 4. 4. 4. 4.]
 [0. 1. 2. 3. 3. 4. 4. 4. 4. 4. 5.]]
longest common subsequent string is :  helod


## Dynamic Programming-0/1 Knapsack Problem

In [32]:
import numpy as np
import pandas as pd
weights=np.array([1,3,5,4])
profits=np.array([4,9,12,11])
items=['A','B','C','D']
data1=pd.DataFrame([items,weights,profits],index=['item','weight','profit'])
data1=data1.T
print(data1)
def knapsac_all_or_none(data,capacity):
    table=np.zeros((len(data)+1,capacity+1))
    for i in range(len(data)):
        for j in range(1,capacity+1):
            if data['weight'][i]<= j:
                table[i+1,j]=max(table[i,j],(data['profit'][i]+table[i,j-data['weight'][i]]))
            else:
                table[i+1,j]=table[i,j]
    print(table)
    i=len(data)-1
    j=capacity
    remain=capacity
    soln=[]
    while remain > 0 :
        if table[i+1,j]>table[i][j]:
            soln.append(data['item'][i])
            remain=remain-data['weight'][i]
            i-=1
            j=remain
        else:
            i-=1
    print(f'items selected: {soln}')
knapsac_all_or_none(data1,8)

  item weight profit
0    A      1      4
1    B      3      9
2    C      5     12
3    D      4     11
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  4.  4.  4.  4.  4.  4.  4.  4.]
 [ 0.  4.  4.  9. 13. 13. 13. 13. 13.]
 [ 0.  4.  4.  9. 13. 13. 16. 16. 21.]
 [ 0.  4.  4.  9. 13. 15. 16. 20. 24.]]
items selected: ['D', 'B', 'A']


## Graph-Prim's Minimum Spanning Tree Algorithm




In [33]:
import numpy as np
labels=np.arange(1,7)
tree=[[0,6.7,5.2,2.8,5.6,3.6],
           [6.7,0,5.7,7.3,5.1,3.2],
           [5.2,5.7,0,3.4,8.5,4],
           [2.8,7.3,3.4,0,8,4.4],
           [5.6,5.1,8.5,8,0,5.6],
           [3.6,3.2,4,4.4,4.6,0]]
tree=pd.DataFrame(tree,columns=labels,index=labels)
print(tree)
print('========================')
def min_spanning_tree(graph):
    selected_nodes=np.zeros(6)
    selected_nodes[0]=1
    edges=0
    while edges < len(graph)-1:
        minimum=float('inf')
        from_node=0
        to_node=0
        for i in range(len(graph)):
            if selected_nodes[i]==1:
                for j in range(len(graph)):
                    if selected_nodes[j]==0 and graph.iloc[i,j]:
                        if minimum > graph.iloc[i,j]:
                            minimum=graph.iloc[i,j]
                            from_node=i
                            to_node=j
        print(from_node+1,'-',to_node+1,':',minimum)
        selected_nodes[to_node]=1
        edges+=1
        
min_spanning_tree(tree)

     1    2    3    4    5    6
1  0.0  6.7  5.2  2.8  5.6  3.6
2  6.7  0.0  5.7  7.3  5.1  3.2
3  5.2  5.7  0.0  3.4  8.5  4.0
4  2.8  7.3  3.4  0.0  8.0  4.4
5  5.6  5.1  8.5  8.0  0.0  5.6
6  3.6  3.2  4.0  4.4  4.6  0.0
1 - 4 : 2.8
4 - 3 : 3.4
1 - 6 : 3.6
6 - 2 : 3.2
6 - 5 : 4.6


## Graph-Breadth First Search Algorithm

In [61]:
from queue import Queue
table={'A':['B','C'],
       'B':['A','D','E'],
       'C':['A','D','F'],
       'D':['B','C','F'],
       'E':['B','F'],
       'F':['C','D','E','H'],
       'H':['F','G','I'],
       'G':['H','I'],
       'I':['G','H']}
def Breadth_First_search(graph):
    queue=Queue()
    visited=['A']
    queue.put('A')
    while queue.qsize() > 0 :
        current_vetex=queue.get()
        destintions=graph[current_vetex]
        for i in range(len(destintions)):
            if destintions[i] not in visited:
                queue.put(destintions[i])
                visited.append(destintions[i])
                print(f'{current_vetex} - {destintions[i]}')
Breadth_First_search(table)

A - B
A - C
B - D
B - E
C - F
F - H
H - G
H - I


## Graph-Depth First Search Algorithm

In [63]:
class vertex:
    def __init__(self,name,neighbors=None,visited=False):
        self.name=name
        self.neighbors=neighbors
        self.visited=visited
        
A,B,C,D,E=vertex('A'),vertex('B'),vertex('C'),vertex('D'),vertex('E'),
F,H,G,I,J=vertex('F'),vertex('H'),vertex('G'),vertex('I'),vertex('J')
A.neighbors=[B,C] 
B.neighbors=[A,D,E]
C.neighbors=[A,D,F]
D.neighbors=[B,C,F]
E.neighbors=[B,F]
F.neighbors=[C,D,E,H]
H.neighbors=[F,G,I]
G.neighbors=[H,I]
I.neighbors=[G,H]
graph=[A,B,C,D,E,F,G,H,I,J]

def Depth_First_search(vertex):
    if not vertex.visited:
        vertex.visited=True
        for neighbor in vertex.neighbors:
            if not neighbor.visited:
                print(f'{vertex.name}-{neighbor.name}')
                Depth_First_search(neighbor)
Depth_First_search(graph[0])


A-B
B-D
D-C
C-F
F-E
F-H
H-G
G-I


## Graph-Dijkstra's Shortest Path Algorithm

In [64]:
class vertex:
    def __init__(self,name,neighbors=None,best_source=None,source_length=float('inf'),total_length=0):
        self.name=name
        self.neighbors=neighbors
        self.best_source=best_source
        self.source_length=source_length
        self.total_length=total_length
        
A,B,C,D,E=vertex('A'),vertex('B'),vertex('C'),vertex('D'),vertex('E'),
F,H,G,I,J=vertex('F'),vertex('H'),vertex('G'),vertex('I'),vertex('J')
A.neighbors=[[B,C,D],[2,4,3]]
B.neighbors=[[E,F,G],[7,4,6]]
C.neighbors=[[E,F,G],[3,2,4]]
D.neighbors=[[E,F,G],[4,1,5]]
E.neighbors=[[H,I],[1,4]]
F.neighbors=[[H,I],[6,3]]
G.neighbors=[[H,I],[3,3]]
H.neighbors=[[J],[3]]
I.neighbors=[[J],[4]]
J.neighbors=[[],[]]
A.source_length=0
graph=[A,B,C,D,E,F,G,H,I,J]

def Dijkstras_Shortest_Path(graph):
    for i in graph:
        for j in graph:
            if i in j.neighbors[0]:
                if j.neighbors[1][j.neighbors[0].index(i)]<i.source_length:
                    i.source_length=j.neighbors[1][j.neighbors[0].index(i)]
                    i.best_source=j.name
                    i.total_length=i.source_length+j.total_length
    for vertex in graph:
        print(f'[{vertex.best_source}-{vertex.name}-{vertex.source_length}]')
    route=graph[-1].name
    i=len(graph)-1
    while route[0] != graph[0].name:
        for k in graph:
            if k.name == graph[i].best_source:
                route=k.name+'-'+route
                i=graph.index(k)       
    print('============================')
    print('shortest-route is [',route,']'' cost= ',graph[-1].total_length)
Dijkstras_Shortest_Path(graph)

[None-A-0]
[A-B-2]
[A-C-4]
[A-D-3]
[C-E-3]
[D-F-1]
[C-G-4]
[E-H-1]
[F-I-3]
[H-J-3]
shortest-route is [ A-C-E-H-J ] cost=  11
